import { getProject,saveProject } from '../../utils/storage';import { CHECK_STATUSES,SEVERITIES,uid } from '../../utils/constants';import { choosePersistentPhotos,removePhoto } from '../../utils/photo';import { CheckRecord } from '../../types/models';
Page({data:{id:'',roomId:'',itemName:'',phase:'入住',p:null as any,record:null as any,original:null as any,statuses:CHECK_STATUSES,severities:SEVERITIES,statusIndex:0,severityIndex:0,comparisons:['无变化','已经修复','新增损坏','状态不确定'],comparisonIndex:0},
onLoad(o:any){this.setData({id:o.id,roomId:o.roomId,itemName:decodeURIComponent(o.item),phase:o.phase||'入住'});wx.setNavigationBarTitle({title:decodeURIComponent(o.item)});this.load();},
load(){const p=getProject(this.data.id);if(!p)return;let record=p.checks.find(c=>c.roomId===this.data.roomId&&c.itemName===this.data.itemName&&c.phase===this.data.phase);if(!record)record={id:uid('check'),roomId:this.data.roomId,itemName:this.data.itemName,phase:this.data.phase,status:'尚未检查',photos:[],note:'',severity:'轻微',checkedAt:Date.now(),comparison:'状态不确定'} as CheckRecord;const original=p.checks.find(c=>c.roomId===this.data.roomId&&c.itemName===this.data.itemName&&c.phase==='入住');this.setData({p,record,original,statusIndex:CHECK_STATUSES.indexOf(record.status),severityIndex:SEVERITIES.indexOf(record.severity),comparisonIndex:this.data.comparisons.indexOf(record.comparison||'状态不确定')});},
status(e:any){const i=Number(e.detail.value);this.setData({statusIndex:i,'record.status':CHECK_STATUSES[i]});},severity(e:any){const i=Number(e.detail.value);this.setData({severityIndex:i,'record.severity':SEVERITIES[i]});},comparison(e:any){const i=Number(e.detail.value);this.setData({comparisonIndex:i,'record.comparison':this.data.comparisons[i]});},editNote(){wx.showModal({title:'问题说明',content:this.data.record.note||'',editable:true,placeholderText:'描述位置、大小、是否影响使用等',confirmText:'保存',success:(r:any)=>{if(r.confirm)this.setData({'record.note':r.content||''});}});},
async photos(){try{wx.showLoading({title:'正在保存照片'});const a=await choosePersistentPhotos(9-this.data.record.photos.length);this.setData({'record.photos':this.data.record.photos.concat(a)});}catch(e){wx.showToast({title:'未能选择照片',icon:'none'});}finally{wx.hideLoading();}},delPhoto(e:any){const i=e.currentTarget.dataset.i;removePhoto(this.data.record.photos[i]);const a=this.data.record.photos.slice();a.splice(i,1);this.setData({'record.photos':a});},preview(e:any){wx.previewImage({urls:this.data.record.photos.map((x:any)=>x.path),current:e.currentTarget.dataset.path});},
save(){const p=this.data.p;const r=this.data.record;r.checkedAt=Date.now();const i=p.checks.findIndex((x:any)=>x.id===r.id);if(i<0)p.checks.push(r);else p.checks[i]=r;const abnormal=!['正常','尚未检查','房屋内没有此项'].includes(r.status);if(abnormal){let issue=p.issues.find((x:any)=>x.phase===r.phase&&x.room===p.rooms.find((x:any)=>x.id===r.roomId)?.name&&x.itemName===r.itemName);if(!issue){issue={id:uid('issue'),room:p.rooms.find((x:any)=>x.id===r.roomId)?.name||'',itemName:r.itemName,type:r.status,description:r.note,photos:r.photos,severity:r.severity,recordedAt:r.checkedAt,phase:r.phase,resolved:false,resolution:''};p.issues.unshift(issue);}else Object.assign(issue,{type:r.status,description:r.note,photos:r.photos,severity:r.severity,recordedAt:r.checkedAt});}saveProject(p);wx.showToast({title:'检查记录已保存'});setTimeout(()=>wx.navigateBack(),500);},
del(){wx.showModal({title:'删除检查记录？',content:'照片文件不会立即清理，可在“我的”中清理未使用照片。',success:(x:any)=>{if(x.confirm){this.data.p.checks=this.data.p.checks.filter((r:any)=>r.id!==this.data.record.id);saveProject(this.data.p);wx.navigateBack();}}});}
});
